window.EQUIPMENT = [
  { key: "mag556",  label: "5.56 MAG", bando: "4" },
  { key: "mag762",  label: "7.62 MAG", bando "" },
  { key: "link762", label: "7.62 LINK" },
  { key: "frag",    label: "FRAG" },
  { key: "smkWhite", label: "White Smoke" },
  { key: "smkYellow", label: "Yellow Smoke" },
  { key: "bandagePacking", label: "PACKING BANDAGE" },
  { key: "bandageElastic", label: "ELASTIC BANDAGE" },
  { key: "bandageQuikclot", label: "QuikClot BANDAGE" },
  { key: "tq",      label: "TQ" },
  { key: "nlaw",    label: "NLAW" },
  { key: "asm",     label: "ASM" },
  { key: "40mmSmk",     label: "40mm" },
  { key: "40mmHE",     label: "40mm HE" },
];
